services:
  postgres:
    # image: postgres:18.4-alpine
    image: postgres:17-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - ecommerce-net

  api-gateway:
    build: ./api-gateway
    container_name: ecommerce-api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env.docker
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
    networks:
      - ecommerce-net

  user-service:
    build: ./user-service
    container_name: ecommerce-user-service
    ports:
      - "3001:3001"
    env_file: ./user-service/.env.docker
    depends_on:
      - postgres
    networks:
      - ecommerce-net

  product-service:
    build: ./product-service
    container_name: ecommerce-product-service
    ports:
      - "3002:3002"
    env_file: ./product-service/.env.docker
    depends_on:
      - postgres
    networks:
      - ecommerce-net

  order-service:
    build: ./order-service
    container_name: ecommerce-order-service
    ports:
      - "3003:3003"
    env_file: ./order-service/.env.docker
    depends_on:
      - postgres
      - product-service
    networks:
      - ecommerce-net

  payment-service:
    build: ./payment-service
    container_name: ecommerce-payment-service
    ports:
      - "3004:3004"
    env_file: ./payment-service/.env.docker
    depends_on:
      - postgres
      - order-service
    volumes:
      - payment_uploads:/app/uploads
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  postgres_data:
  payment_uploads:
